---
- name: Create Basic Server
  hosts: localhost
  connection: local
  gather_facts: False
  user: root
  vars:
    hcloud_token: yourtoken
    a3servername: arma3server
    hc:
      - hc1
      - hc2
  tasks:
    - name: Create a the ArmA 3 Server
      hcloud_server:
        api_token: "{{ hcloud_token }}"
        name: "{{ a3servername }}"
        server_type: ccx21
        image: centos-7
        state: present
      register: a3server

    - set_fact:
        a3srvip: "{{ a3server.hcloud_server.ipv4_address }}"

    - name: Create the mod volume for a3server
      hcloud_volume:
        api_token: "{{ hcloud_token }}"
        name: a3server-volume
        size: 50
        server: "{{ a3servername }}"
        automount: no
        format: xfs
        state: present

    - name: Create a the ArmA 3 Server
      hcloud_server:
        api_token: "{{ hcloud_token }}"
        name: "arma3{{ item }}"
        server_type: cx11
        image: centos-7
        state: present
      register: a3server
      loop: "{{ hc }}"

    - name: Create the mod volume for headlessclients
      hcloud_volume:
        api_token: "{{ hcloud_token }}"
        name: "{{ item }}-volume"
        size: 50
        server: "arma3{{ item }}"
        automount: no
        format: xfs
        state: present
      loop: "{{ hc }}"
