---
- name: Create Basic Server
  hosts: localhost
  connection: local
  gather_facts: False
  user: root
  vars:
    hcloud_token: yourtoken
    a3servername: arma3server
    hc:
      - hc1
      - hc2
  tasks:
    - name: Remove a the ArmA 3 Server
      hcloud_server:
        api_token: "{{ hcloud_token }}"
        name: arma3server
        server_type: ccx21
        image: centos-7
        state: absent

    - name: remove mod volume for a3server
      hcloud_volume:
        api_token: "{{ hcloud_token }}"
        name: a3server-volume
        server: "{{ a3servername }}"
        state: absent

    - name: remove a the ArmA 3 Server
      hcloud_server:
        api_token: "{{ hcloud_token }}"
        name: arma3{{ item }}
        state: absent
      loop: "{{ hc }}"

    - name: remove mod volume for headlessclients
      hcloud_volume:
        api_token: "{{ hcloud_token }}"
        name: a3server-volume
        server: "arma3{{ item }}"
        state: absent
      loop: "{{ hc }}"
