---
- name: Create Basic Server
  hosts: localhost
  connection: local
  gather_facts: False
  user: root
  vars:
    hcloud_token: VALUE_SPECIFIED_IN_NO_LOG_PARAMETER
    a3servername: a3srv
    reposize: 50
    hc:
      - hc1
      - hc2
      - hc3
  tasks:
    - name: Remove a the ArmA 3 Server
      hcloud_server:
        api_token: "{{ hcloud_token }}"
        name: "{{ a3servername }}"
        server_type: ccx21
        image: centos-7
        state: absent

    - name: remove a the ArmA 3 HC
      hcloud_server:
        api_token: "{{ hcloud_token }}"
        name: "a3{{ item }}"
        state: absent
      loop: "{{ hc }}"
      when: hc is defined
