---
- name: Create the ArmA 3 Server
  hcloud_server:
    api_token: "{{ hcloud_token }}"
    name: "{{ a3servername }}"
    server_type: ccx21
    image: centos-7
    state: present
    location: "{{ location }}"
    ssh_keys:
      - {{ public_key }}
    labels:
      a3: "{{ a3servername }}"
  register: a3srv_fact

- name: Create mod volume for ArmA 3 Server
  hcloud_volume:
    api_token: "{{ hcloud_token }}"
    name: "{{ a3servername }}-mods"
    size: "{{ reposize }}"
    server: "{{ a3servername }}"
    automount: no
    format: xfs
    state: present

- name: Create ArmA 3 HC
  hcloud_server:
    api_token: "{{ hcloud_token }}"
    name: "a3{{ item }}"
    server_type: cx11
    image: centos-7
    state: present
    location: "{{ location }}"
    ssh_keys:
      - {{ public_key }}
    labels:
      a3: "a3{{ item }}"
  loop: "{{ hc }}"
  when: hc is defined
  register: hc_fact

- name: Create the mod volume for HC
  hcloud_volume:
    api_token: "{{ hcloud_token }}"
    name: "a3{{ item }}-mods"
    size: "{{ reposize }}"
    server: "a3{{ item }}"
    automount: no
    format: xfs
    state: present
  loop: "{{ hc }}"
  when: hc is defined
